services:
  app:
    container_name: nodejs2022Q2-service-app
    build: .
    image: oakov/nodejs2022q2-service:app
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: ${POSTGRES_DB:-rest}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: postgres
    restart: always

  postgres:
    container_name: nodejs2022Q2-service-postgres-db
    build: ./database/
    image: oakov/nodejs2022q2-service:postgres-db
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: ${POSTGRES_DB:-rest}
      PGDATA: /var/lib/postgresql/data
    restart: always
    command: postgres -c logging_collector=on

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
